version: 2.1

jobs:
  mend_scan:
    macos:
      xcode: "15.2.0"
    environment:
      MAX_HEAP_SIZE: 4096m
      HEAP_NEWSIZE: 1024m
    steps:
      - checkout

      - run:
          name: Install Mend CLI
          command: |
            sudo curl https://downloads.mend.io/cli/darwin_arm64/mend -o /usr/local/bin/mend && sudo chmod +x /usr/local/bin/mend

      - run:
          name: Run Mend dependency scan
          command: |
            mend version
            sudo mend version
            echo "Mend scan logs:"
            ls -l "$HOME/.mend/logs/sca"

workflows:
  mend_scan_workflow:
    jobs:
      - mend_scan